#!/usr/bin/env python3
"""Emit inventory/provenance.jsonl.

Rows are curated mechanism-level changes. Every row's `statedReason` is copied
verbatim from one of: the commit message body, the skill/doc file text the
commit wrote, or a `.mise/` artifact (goals.md / _friction.md) on the branch
that produced the commit. `version` is the plugin.json version in effect at
that commit (from tools/commit_table.sh output). `laterChurn` lists shas that
reworked or reverted the same mechanism.

Usage: python3 gen_provenance.py > ../inventory/provenance.jsonl
"""
import json
import sys

# (sha, date, version, file, anchor, change, what, statedReason, trigger, laterChurn)
ROWS: list[tuple] = [
    # ---------------------------------------------------------------- pre-mise
    ("bc94c76", "2026-03-16", "", ".claude/skills/", "nine workflow skills + workflow-config.md", "added",
     "Imported 9-skill workflow set (goals/mock/requirements/architecture/plan/execute/fix-bug) + config template",
     "A set of Claude Code skills for structured feature development ... All skills reference a central workflow-config.md template with placeholders for project-specific paths, commands, test conventions, and related skills.",
     "unknown", ["50c377e"]),
    ("620fd53", "2026-04-25", "", ".claude/skills/execute-implementation-plan/implement_task.md", "subject task file", "added",
     "Bind the task file path to the dequeued TODO entry instead of an unbound $TASK_FILE",
     "implement_task.md referenced $TASK_FILE with no binding.", "unknown", ["50c377e"]),
    ("d7eaee0", "2026-04-25", "", ".claude/skills/write-implementation-plan/SKILL.md", "Create the implementation plan folder", "added",
     "Explicit folder-creation step before writing exploration notes into it",
     "write-implementation-plan step 4 wrote _exploration_notes.md into implementation_plan/ before that folder existed",
     "unknown", []),
    ("3b8eef8", "2026-04-25", "", ".claude/skills/extract-requirements-from-mock/SKILL.md", "Extract requirements", "reworked",
     "Unify requirements.md shape: REQ-<CAT>-<N> ids, MUST/SHOULD/MAY, Out of Scope, acceptance table",
     "extract-requirements-from-mock and write-requirements produced incompatible requirements.md formats, but write-architecture consumes either one and assumes a single shape.",
     "unknown", ["ffc5890", "a42137b", "d313ce6"]),
    ("af4dcf8", "2026-04-25", "", "README.md", "# Interactivity", "added",
     "README section listing which skills need a human vs. are unattended-safe",
     "The README pitches overnight autonomous coding, but several skills hard-block on user confirmation",
     "unknown", ["50c377e"]),
    ("a7cc237", "2026-04-25", "", ".claude/skills/execute-implementation-plan/SKILL.md", "tasks: YAML block", "added",
     "Machine-readable tasks: YAML in 00_overview.md as the executor's source of truth",
     "execute-implementation-plan parsed the human-readable Task Index table to build its TODO list, which made the executor brittle to any drift in table formatting.",
     "speculative", ["c926cc3"]),
    ("c4835cd", "2026-04-25", "", ".claude/skills/execute-implementation-plan/implement_task.md", "CRITICAL: Triage failures before fixing them", "reworked",
     "Replace 'no pre-existing failures' with base-branch triage and a blocker exit",
     "implement_task.md previously declared \"ALL failures are your responsibility\" with no escape hatch, which caused scope creep on long autonomous runs (the agent would chase unrelated, pre-existing bugs).",
     "named-failure-in-a-real-run", ["972e826", "50c377e"]),
    ("598aa7c", "2026-04-25", "", ".claude/workflow-config.md", "config file location", "reworked",
     "Move workflow-config.md out of .claude/skills/ and repoint 9 files",
     ".claude/skills/ is conventionally for skill folders only, but the workflow-config template lived alongside them as a stray file.",
     "refactor", ["50c377e"]),
    ("e94148a", "2026-04-25", "", ".claude/workflow-config.md", "## Quality commands", "reworked",
     "Quality slots accept a list of commands, run in order, stop at first failure",
     "Real projects often have multi-step quality pipelines (build -> lint -> test, sometimes per package).",
     "speculative", ["3bf63b2", "771e196"]),
    ("823501d", "2026-04-25", "", ".claude/workflow-config.md", "UI_CODE_ROOT", "added",
     "UI code root slot so mocks can read the real UI",
     "none", "unknown", ["3bf63b2"]),
    ("aee7cd1", "2026-04-25", "", ".claude/skills/", "argument-hint", "reworked",
     "Standardize argument-hint syntax across all skills",
     "none", "refactor", []),
    ("d221a55", "2026-04-25", "", ".claude/skills/extract-requirements-from-mock/SKILL.md", "conversation history", "added",
     "Handle an empty conversation history",
     "none", "unknown", []),
    ("3bf63b2", "2026-05-05", "", ".claude/workflow-config.md", "Quality commands / Product identity examples", "removed",
     "Drop multi-step and single-command examples and the UI_CODE_ROOT example (23 lines)",
     "Drop the multi-step-pipeline and single-command examples from Quality commands; the bulleted slot definitions are self-explanatory.",
     "owner-preference", []),
    ("1ccaa16", "2026-05-05", "", ".claude/workflow-config.md", "## Backlog", "added",
     "Optional Backlog section read verbatim by /next when nothing is in flight",
     "The /next skill reads this section to fetch pending work from an external tracker (Todoist, Linear, Jira, a markdown file, etc.) when no feature is in progress.",
     "owner-preference", []),
    ("accf5e3", "2026-05-05", "", ".claude/skills/setup-workflow/SKILL.md", "# Set up workflow", "added",
     "Interactive /setup-workflow that fills the config's placeholders",
     "Walks the user through .claude/workflow-config.md and replaces <PLACEHOLDER> values interactively.",
     "owner-preference", ["3cc5680", "50c377e"]),
    ("0190e87", "2026-05-05", "", ".claude/skills/next/SKILL.md", "# Next", "added",
     "/next orchestrator: proceed/explain/description modes, stage detection by artifact presence, .next-current pointer",
     "The single entry point to start or continue feature work. Reads .claude/workflow-config.md, finds or selects the active feature, and either runs or just describes the next slash command in the workflow.",
     "owner-preference", ["50c377e", "57655da"]),
    ("3cc5680", "2026-05-13", "", ".claude/skills/setup-workflow/SKILL.md", "global workflow-config template", "reworked",
     "Bootstrap the project config from ~/.claude/workflow-config.template.md",
     "When the per-project workflow-config.md is missing, the skill now tells users to copy from ~/.claude/workflow-config.template.md (deployed alongside the global skills) instead of pointing them back to the workflow-skills repo.",
     "owner-preference", ["50c377e"]),
    ("933797a", "2026-05-13", "", ".claude/skills/update-workflows/SKILL.md", "# Update workflows", "added",
     "/update-workflows copies the repo's skills to ~/.claude/",
     "Provides a one-step way to redeploy this repo's workflow skills and workflow-config template to ~/.claude/, so changes made here propagate to every project on the machine without manual cp commands.",
     "owner-preference", ["50c377e"]),
    ("44d2cd4", "2026-05-13", "", ".claude/skills/_shared/interaction.md", "# Shared interaction conventions", "added",
     "Shared interaction file: normal/expert verbosity, 1-3 questions per turn, numbered questions + lettered options",
     "Introduces .claude/skills/_shared/interaction.md as a single source of truth for how workflow skills should talk to the user: terse-vs-verbose mode, small-chunk question pacing, and a numbered-question / lettered-option format that lets the user reply with compact answers like \"1a,2c\".",
     "owner-preference", ["4bd508d", "50c377e", "2527288"]),
    ("ddc3b52", "2026-05-13", "", ".claude/skills/execute-implementation-plan/SKILL.md", "## Stopping rules / Plan vs. skill precedence", "added",
     "Every task ends green; explicit stopping rules; task notes never beat safety rules; batched clarifying questions",
     "Three connected changes so /write-implementation-plan and /execute-implementation-plan run longer without stopping for user input",
     "owner-preference", ["ffc5890", "642a30b"]),
    ("4bd508d", "2026-05-13", "", ".claude/skills/_shared/interaction.md", "## Recommendations", "added",
     "Every question turn ends with a Recommend: line the user can accept in one reply",
     "Skills end each question turn with a \"Recommend: ...\" line so the user can accept the model's read in one reply.",
     "owner-preference", ["50c377e", "04a3681", "6d50aa9"]),
    ("f365995", "2026-05-14", "", ".claude/workflow-config.md", "## Code conventions", "added",
     "Move hardcoded Python-style rules out of implement_task.md into an optional config section",
     "These are project/language conventions, not workflow rules, so they violated the \"skills agnostic, project specifics in workflow-config\" split.",
     "refactor", ["50c377e"]),
    ("972e826", "2026-05-14", "", ".claude/skills/execute-implementation-plan/implement_task.md", "CRITICAL: No pre-existing failures", "removed",
     "Revert c4835cd's triage escape hatch; all failures are the agent's again",
     "The triage escape hatch let the agent declare too many failures as pre-existing, undermining the autonomous-run safety net.",
     "named-failure-in-a-real-run", ["50c377e"]),
    ("ffc5890", "2026-05-14", "", ".claude/skills/", "Stopping rules / step 4 / clarifying questions", "removed",
     "Compression pass: 13-line stopping rules -> one paragraph; 32 lines cut across 4 skills",
     "Surgical pass over files that existed on main: keep every correctness fix and every new capability, but drop prose that didn't earn its weight.",
     "owner-preference", []),
    ("642a30b", "2026-05-14", "", ".claude/skills/execute-implementation-plan/implement_task.md", "step 4 wording", "removed",
     "Revert step 4 verification wording to main's",
     "none", "owner-preference", []),
    ("771e196", "2026-05-14", "", ".claude/workflow-config.md", "list-of-commands semantics", "reworked",
     "A failing command in a list means fix-and-retry, not terminate",
     "Clarify list-of-commands semantics: fix-and-retry, not terminate", "unknown", []),
    ("a42137b", "2026-05-14", "", ".claude/skills/extract-requirements-from-mock/SKILL.md", "Acceptance Criteria", "removed",
     "Drop the acceptance-criteria table from the mock-extraction path",
     "Drop redundant Acceptance Criteria from extract-requirements-from-mock", "refactor", []),
    ("80ffb3f", "2026-05-14", "", ".claude/skills/setup-workflow/SKILL.md", "press enter to skip", "reworked",
     "Replace 'press enter to skip' with chat-friendly phrasing",
     "none", "unknown", []),
    ("c926cc3", "2026-05-14", "", ".claude/skills/execute-implementation-plan/SKILL.md", "tasks: YAML block", "removed",
     "Revert the machine-readable tasks: YAML block added 19 days earlier",
     "none", "unknown", []),

    # ------------------------------------------------------------------- 1.0.0
    ("50c377e", "2026-07-13", "1.0.0", "skills/next/SKILL.md", "# Next (single mise:next command)", "reworked",
     "Nine skills collapse into one user-invoked skill with stages/, references/ and a TS state engine",
     "Plugin restructure: the old .claude/skills/* set becomes a single user-invoked skill (skills/next) with stages/, references/, and a TypeScript state engine",
     "refactor", ["c9d5646", "58d4b1a", "50b5f2b", "57655da"]),
    ("50c377e", "2026-07-13", "1.0.0", "skills/next/scripts/state.ts", "state engine: report + approve", "added",
     "476-line TS state engine, two commands, approval hashes and a downstream-clearing cascade",
     "State engine redesign - two commands (report, approve), three ideas", "refactor", ["50b5f2b"]),
    ("50c377e", "2026-07-13", "1.0.0", "skills/next/scripts/state.ts", "done/ directory as completion record", "added",
     "Task completion is a file move into implementation_plan/done/; tasks_done/set/reopen deleted",
     "Task completion lives in the filesystem: finished task files move to implementation_plan/done/, scoped to one approved plan version ... tasks_done, set, reopen, and the stale-task gate are gone.",
     "refactor", []),
    ("50c377e", "2026-07-13", "1.0.0", "skills/next/scripts/state.ts", "route rides on the goals approval", "added",
     "approve goals route=<full|direct|bugfix> makes an unrouted goals approval unrepresentable",
     "The route rides on the goals approval (approve goals route=...), so a goals approval without a route is unrepresentable; route_lost and the approve-mock side effect are gone.",
     "refactor", []),
    ("50c377e", "2026-07-13", "1.0.0", "skills/next/scripts/state.ts", "no recovery by inference", "removed",
     "Broken/missing state file is an error naming the user's options; salvage tier deleted",
     "No recovery by inference: a broken or unexpectedly missing state file is an error naming the user's options ... the salvage/inference tier and orphan_task_files are gone.",
     "refactor", []),
    ("50c377e", "2026-07-13", "1.0.0", "skills/next/stages/execute.md", "Baseline gate", "added",
     "Format/Check/Unit tests before the plan's first task only; mid-plan red is the work's to fix",
     "Execute stage: baseline gate scoped to the plan's first task (mid-plan red is the work's to fix, never \"pre-existing\")",
     "refactor", []),
    ("50c377e", "2026-07-13", "1.0.0", "skills/next/stages/execute.md", "stuck vs blocked retry routing", "added",
     "A stuck implementer gets one fresh-context retry; a blocked one stops immediately",
     "a stuck implementer gets one fresh-context retry, a blocked one stops immediately", "speculative", ["57655da", "b13fa5c"]),
    ("50c377e", "2026-07-13", "1.0.0", "skills/next/references/interaction.md", "## Gates - exactly two human gates", "added",
     "Goals(+mock) gate and acceptance pass are the only human gates; everything between self-approves",
     "There are exactly two **human gates**: the goals(+mock) gate at the start, and the acceptance pass at the end. Every stage in between self-approves through the critic gate below and continues in the same session - the user is never asked to approve requirements or plans.",
     "owner-preference", ["57655da"]),
    ("50c377e", "2026-07-13", "1.0.0", "skills/next/references/interaction.md", "### The critic gate (requirements and plan stages)", "added",
     "Fresh-context critic subagent per artifact; defects -> revise; 3 rounds max then stop",
     "Defects -> revise and re-dispatch a fresh critic. After **3 rounds** without a pass, stop and present the artifact and the remaining defects to the user - an honest stall beats looping.",
     "speculative", ["f374756", "58d4b1a", "4e828af", "57655da"]),
    ("50c377e", "2026-07-13", "1.0.0", "skills/next/references/interaction.md", "### Assumptions instead of questions", "added",
     "Stages past goals never ask; non-obvious inferences go in an Assumptions section covered by the approval hash",
     "Stages past the goals gate never ask clarifying questions. Infer defaults from the goals, mocks, codebase, and `.claude/mise-config.md`, and record every non-obvious inference in an **Assumptions** section",
     "owner-preference", ["57655da"]),
    ("50c377e", "2026-07-13", "1.0.0", "skills/next/stages/execute.md", "fresh reviewer subagent per task", "added",
     "Per-task fresh-context reviewer, one review/fix round per task",
     "On success, dispatch a fresh reviewer subagent (fresh context catches what the author's context rationalizes away).",
     "speculative", ["57655da", "b13fa5c"]),
    ("50c377e", "2026-07-13", "1.0.0", "skills/next/stages/execute.md", "Acceptance pass, then cleanup", "added",
     "Acceptance subagent returns a per-requirement checklist; on confirmation the mise directory is deleted",
     "On the user's confirmation, clean up: delete the mise directory entirely and commit the deletion ... the artifacts served their purpose",
     "owner-preference", ["50b5f2b", "58d4b1a", "57655da"]),
    ("50c377e", "2026-07-13", "1.0.0", "skills/next/stages/setup.md", "mise-config.md interview", "reworked",
     "Setup interviews and writes a minimal .claude/mise-config.md; reference is never copied into projects",
     "Instruction files trimmed so every rule has one home; setup commits the generated config; no-e2e projects get a blanket Test exception at setup.",
     "refactor", ["c9d5646", "50b5f2b", "9a8634f", "57655da", "b13fa5c"]),
    ("50c377e", "2026-07-13", "1.0.0", "skills/next/stages/", "architecture stage", "removed",
     "The write-architecture stage is dropped: README goes from 5 mentions of architecture to 0",
     "none", "unknown", []),
    ("50c377e", "2026-07-13", "1.0.0", ".claude/workflow-config.md", "## Code conventions", "removed",
     "Config's code-conventions section deleted; repo-wide conventions move to CLAUDE.md",
     "There is no code-conventions section: repo-wide conventions belong in `CLAUDE.md`, which every agent - including fresh-context subagents - loads automatically.",
     "refactor", []),
    ("50c377e", "2026-07-13", "1.0.0", "docs/skill-authoring.md", "# Skill authoring", "added",
     "New authoring guide for the instruction files (45 lines)",
     "docs consolidate into README + skill-authoring guide + the engine spec (docs/state-machine.md)",
     "refactor", ["f5e9b07", "b13fa5c"]),

    # ------------------------------------------------------------- 1.0.1-1.3.0
    ("d313ce6", "2026-07-14", "1.0.1", "skills/next/stages/implement_task.md", "REQ-* IDs never in code", "added",
     "Ban REQ-* traceability ids from comments, identifiers, test names and strings; add to self-review",
     "Implement-task stage now explicitly prohibits REQ-* traceability IDs in code (comments, identifiers, test names, strings) and adds them to the self-review checklist",
     "unknown", ["57655da"]),
    ("f374756", "2026-07-15", "1.1.0", "skills/next/references/interaction.md", "### The critic gate (requirements and plan stages)", "reworked",
     "Severity tags (blocking/minor/informative); pass = zero blocking; stall on non-decreasing blocking count + 5-round backstop",
     "**Pass = a report with zero blocking findings** - a fresh critic can always find _something_, so \"no findings at all\" is never the bar.",
     "unknown", ["58d4b1a", "4e828af", "57655da"]),
    ("f374756", "2026-07-15", "1.1.0", "skills/next/stages/goals.md", "1. Critique (working notes)", "added",
     "The goals critique is internal working notes, surfaced only as questions or direct edits",
     "The critique is working notes, never output - do not present it as a standalone review.",
     "unknown", ["57655da"]),
    ("f374756", "2026-07-15", "1.1.0", "skills/next/stages/goals.md", "Cover the canonical states", "added",
     "Mocks must cover empty, loading, error placement, and per-action success/failure",
     "A state skipped here becomes a requirements-stage assumption instead of a user decision.",
     "unknown", ["a4e3846", "57655da"]),
    ("a4e3846", "2026-07-16", "1.2.0", "skills/next/stages/goals.md", "mock IDs / New Concepts", "added",
     "Each mock gets a unique ID; a mental-model audit records surviving new concepts in mocks.context.md",
     "Audit every concept the mock introduces: genuinely new, worth its learning cost, or internals leaking into the UI? ... an unlisted concept becomes an assumption instead of a user decision.",
     "unknown", ["57655da"]),
    ("c9d5646", "2026-07-17", "1.3.0", "skills/next/references/config-reference.md", "Branch convention", "added",
     "Required Branch convention config value; new work creates the branch, never runs on default",
     "Starting new work now ensures a work branch: on the default branch it creates one from the config's new required Branch convention value; on any other branch it asks whether to reuse it. Missing convention re-fires the config gate.",
     "unknown", ["58fed2b", "57655da"]),

    # ------------------------------------------------------------------- 1.4.0
    ("58d4b1a", "2026-07-18", "1.4.0", "skills/next/stages/retrospective.md", "# Retrospective", "added",
     "Post-acceptance retrospective subagent proposes minimal guidance edits routed to guide/config/CLAUDE.md/new doc/plugin candidate",
     "After acceptance confirmation and before cleanup, a fresh-context retrospective subagent mines the run for guidance improvements and proposes minimal edits routed to their natural home",
     "speculative", ["57655da", "b13fa5c"]),
    ("58d4b1a", "2026-07-18", "1.4.0", "skills/next/references/interaction.md", "### The friction log", "added",
     "_friction.md: one line per friction event; only the retrospective reads it",
     "Raw material comes from a new friction log (_friction.md): critic gates record multi-round passes and stalls, execute records task failures, reviewer defects, and acceptance items the user flags. Only the retrospective reads it, so it costs later stages nothing.",
     "speculative", ["4e828af", "57655da"]),
    ("58d4b1a", "2026-07-18", "1.4.0", "skills/next/references/config-reference.md", "Retrospective: off", "added",
     "Top-level opt-out line for the retrospective",
     "Opt out with a top-level `Retrospective: off` config line.", "speculative", []),

    # ------------------------------------------------------------------- 1.5.0
    ("50b5f2b", "2026-07-23", "1.5.0", "skills/next/references/config-reference.md", "Ship: pr | merge (<style>) | off", "added",
     "Ship step after cleanup, style recorded at setup and never assumed",
     "Shipping is now part of the pipeline: after the cleanup commit the close-out ships per the config's Ship value (pr | merge (<style>) | off, asked at setup; the merge style is a recorded choice, never assumed).",
     "owner-preference", ["57655da"]),
    ("50b5f2b", "2026-07-23", "1.5.0", "CLAUDE.md", "Never open a pull request ... any branch whose tree contains `.mise/`", "added",
     "Setup writes a CLAUDE.md guard against PR/merge of in-flight branches",
     "Setup also writes a CLAUDE.md guard so sessions outside the workflow refuse to PR/merge any branch whose tree still contains the mise directory.",
     "speculative", []),
    ("50b5f2b", "2026-07-23", "1.5.0", "skills/next/scripts/state.ts", "accepted hash / close_out", "added",
     "Acceptance confirmation recorded as a hash so an interrupted close-out resumes at the retrospective",
     "report returns `close_out` while the record matches, so an interrupted close-out resumes at the retrospective instead of re-running the pass.",
     "speculative", []),

    # ------------------------------------------------------------------- 1.6.0
    ("9a8634f", "2026-07-28", "1.5.0", "skills/next/references/config-reference.md", "## Models", "added",
     "Optional Models section maps 6 subagent roles to models; unassigned roles inherit the session model",
     "An optional ## Models section in .claude/mise-config.md maps subagent roles (implementer, reviewer, critic, acceptance, explore, retrospective) to models ... Setup interviews for it, suggesting generation roles on opus with quality gates on the session model.",
     "owner-preference", ["57655da"]),
    ("9a8634f", "2026-07-28", "1.5.0", "CLAUDE.md", "A user-visible change updates `README.md` in the same run", "added",
     "Repo rule: user-visible changes must update README in the same run",
     "The README is the user's only description of the config surface and the stage list, so a skill-file-only change ships an undocumented feature.",
     "unknown", []),
    ("28b1acd", "2026-07-28", "1.6.0", ".claude-plugin/plugin.json", "version 1.6.0", "reworked",
     "Version bump shipping the Models section (the feature commit did not bump)",
     "none", "unknown", ["cb905af"]),

    # ------------------------------------------------------------------- 1.7.0
    ("f7656c2", "2026-08-14", "1.6.0", "skills/next/references/interaction.md", "### The critic gate - points 3 and 4", "reworked",
     "Count-based stall replaced by recurrence tracking: fresh/recurring classification, 3 stall triggers, 5/8 round budgets",
     "Points 3 and 4 ... now decide continuation by defect identity instead of blocking counts, which misfired whenever a round of all-new findings matched or exceeded the previous round's count even though every prior fix had landed.",
     "named-failure-in-a-real-run", ["b13fa5c"]),
    ("4e828af", "2026-08-14", "1.7.0", "skills/next/references/interaction.md", "### The critic gate (requirements and plan stages)", "reworked",
     "Squash of f7656c2+1ba0b07 onto main; README stall annotation synced; version 1.7.0",
     "I often run into the following case. I would like to improve the system so that this does not happen. The stop seems unnecessary. [.mise/goals.md 'Original report', branch feat/critic-stall-heuristic @86b3aa0~1]",
     "named-failure-in-a-real-run", ["b13fa5c"]),
    ("cb905af", "2026-08-14", "1.7.0", "CLAUDE.md", "A user-visible change also bumps `version` in `.claude-plugin/plugin.json`", "added",
     "Retrospective-adopted rule: bump plugin.json version in the same run",
     "Claude Code installs and updates the plugin by version, so a change that ships without a bump never reaches an installed user, and no test or quality gate catches it.",
     "named-failure-in-a-real-run", []),

    # ------------------------------------------------------------------- 2.0.0
    ("f5e9b07", "2026-08-18", "1.7.0", "docs/skill-authoring.md", "v2 writing bar", "reworked",
     "Authoring guide rewritten: drop 'do not terse-ify', adopt the 'would removing this line cause a mistake?' test",
     "Rephrase for a human reader: shorter sentences, one rule per line, rationale only where a rule would otherwise be misapplied; revise `docs/skill-authoring.md` (drop \"do not terse-ify\", adopt the \"would removing this line cause a mistake?\" test). [.mise/goals.md Goal 2.5]",
     "owner-preference", ["f077507", "b13fa5c"]),
    ("387a764", "2026-08-18", "1.7.0", "skills/next/references/config-reference.md", "Checklist: / Task tests: / Review notes", "added",
     "Three new config values: Checklist file (cap 15 rules), scoped Task tests command, Review notes source",
     "A project file of **checkable rules** ... owned by the project and registered in `.claude/mise-config.md` as a required value; the config gate blocks execution without it [.mise/goals.md Goal 1.1]",
     "named-failure-in-a-real-run", ["a0d9a18", "57655da"]),
    ("2527288", "2026-08-18", "1.7.0", "skills/next/roles/critic.md", "# Critic", "added",
     "Interaction reference rewritten; critic gets its own self-contained role file",
     "Restructure by reader: orchestrator-side files (dispatcher + stages) and self-contained **role files** for every fresh-context subagent ... so prompts are no longer composed ad hoc inside `execute.md` and `interaction.md`. [.mise/goals.md Goal 2.2]",
     "owner-preference", ["a39da50"]),
    ("dc1687b", "2026-08-18", "1.7.0", "skills/next/roles/implementer.md", "# Implementer", "added",
     "Self-contained implementer role file replaces stages/implement_task.md",
     "Restructure by reader ... self-contained **role files** for every fresh-context subagent (implementer, reviewer, critic, acceptance, documenter, retrospective) dispatched by path [.mise/goals.md Goal 2.2]",
     "owner-preference", ["3d58711", "133d2de", "b13fa5c"]),
    ("c83ca3a", "2026-08-18", "1.7.0", "skills/next/roles/reviewer.md", "# Reviewer", "added",
     "Reviewer and acceptance role files added",
     "a fresh-context reviewer must be told to flag only correctness/requirement gaps or it will always report something [.mise/goals.md, External guidance]",
     "named-failure-in-a-real-run", ["4a08272", "b13fa5c"]),
    ("f098fb0", "2026-08-18", "1.7.0", "skills/next/roles/documenter.md", "# Documenter", "added",
     "New documenter role: when configured, implementers write no prose and one end-of-plan pass writes it",
     "I would like to have a way to define which model writes comments. This is motivated in the fect that Opus 5 is very good at coding but horrible and anything that has to do with prose or even code comments. [.mise/goals.md Original description item 3]",
     "owner-preference", ["342f25e", "b13fa5c"]),
    ("f098fb0", "2026-08-18", "1.7.0", "skills/next/roles/retrospective.md", "Every correction yields a proposal", "reworked",
     "Retrospective now treats every user correction as a checklist/doc proposal; adds the Review notes source",
     "The retrospective now treats every user correction as a proposal for that checklist ... so feedback you've given once becomes a rule the workflow enforces from then on. [.mise/goals.md Original description item 1]",
     "named-failure-in-a-real-run", ["4051f82", "0d68a8a"]),
    ("33d9e93", "2026-08-18", "1.7.0", "skills/next/stages/execute.md", "## End-of-plan gate", "added",
     "execute.md rewritten as v2 orchestrator; per-task scoped verification, full quality commands moved to an end-of-plan gate",
     "**Per task**: implement ... -> scoped verification (format + check + the task's tests via a new optional config value `Task tests:` ...) ... **Once at the end of the plan**: documenter pass (when configured) -> full quality commands and any e2e/sanity runs -> acceptance pass [.mise/goals.md Goal 4.1-4.2]",
     "named-failure-in-a-real-run", ["d187fd0", "b13fa5c"]),
    ("401d676", "2026-08-18", "1.7.0", "skills/next/stages/plan.md", "Task-size guardrail", "added",
     "Each task modifies at most 5 source files; unjustified breach is blocking for the plan critic",
     "Anthropic's PR-size data shows >1000-line diffs get findings 84% of the time vs 31% for <50 lines [.mise/goals.md, External guidance]; This replaces the \"~2 hours of focused work\" ceiling. [Goal 1.4]",
     "named-failure-in-a-real-run", ["d8cc195"]),
    ("e259176", "2026-08-18", "1.7.0", "skills/next/SKILL.md", "`?` explain mode", "removed",
     "Explain mode cut from the dispatcher (3 mentions -> 0); SKILL.md 2068 -> 1120 words",
     "the `?` explain mode once [used] [.mise/goals.md, Other usage facts]; Behavior cuts and keeps decided at the gate: **cut** the `?` explain mode [Goal 2.4]",
     "named-failure-in-a-real-run", ["8590308"]),
    ("53896d7", "2026-08-18", "2.0.0", "README.md", "v2 surface", "reworked",
     "README documents the v2 surface; plugin version 2.0.0",
     "Version bumps to 2.0.0; README documents every new config value, role, and stage change. [.mise/goals.md, Decisions recorded at the goals gate]",
     "owner-preference", ["daec5ee", "b13fa5c"]),
    ("58fed2b", "2026-08-19", "2.0.0", "skills/next/SKILL.md", "branch question", "reworked",
     "Skip the branch question when the current branch is new and named for the work",
     "correction: review notes on v2 files - ... branch question skipped for a new correctly named branch (fixed) [.mise/_friction.md @a6f5016~1]",
     "named-failure-in-a-real-run", []),
    ("6d50aa9", "2026-08-19", "2.0.0", "skills/next/references/interaction.md", "## Recommendations", "reworked",
     "A reply of `rec` accepts every recommended pick",
     "correction: review notes on v2 files - ... rec shortcut for recommendations (fixed) [.mise/_friction.md @a6f5016~1]",
     "named-failure-in-a-real-run", ["04a3681"]),
    ("278851b", "2026-08-19", "2.0.0", "skills/next/roles/", "<default> in the Docs: commit lookup", "reworked",
     "Reword <default> at three sites (acceptance, execute, documenter)",
     "correction: \"<default>... never its own history\" read as commit-on-main - reworded at three sites (acceptance, execute, documenter) [.mise/_friction.md @a6f5016~1]",
     "named-failure-in-a-real-run", ["b13fa5c"]),
    ("04a3681", "2026-08-19", "2.0.0", "skills/next/references/interaction.md", "## Recommendations", "reworked",
     "Show the rec hint on every Recommend line",
     "correction: Recommend line should show the rec hint itself (fixed) [.mise/_friction.md @a6f5016~1]",
     "named-failure-in-a-real-run", []),
    ("0d68a8a", "2026-08-19", "2.0.0", "skills/next/roles/retrospective.md", "checklist routing priority", "reworked",
     "Route corrections: documented-but-ignored or mechanical rules to the checklist, new conventions to docs first",
     "correction: checklist routing priority - documented-but-ignored or mechanical rules to the checklist, new conventions to durable docs first (fixed, option b) [.mise/_friction.md @a6f5016~1]",
     "named-failure-in-a-real-run", []),
    ("57655da", "2026-08-19", "2.0.0", "skills/next/", "mise 2.0.0 squash", "reworked",
     "Squash: checklist, 6 role files, documenter, end-of-plan gate, Task tests, guardrail; 11267 -> 9795 words",
     "mise 2.0.0: project review checklist, documenter role, end-of-plan gate, halved instruction files",
     "owner-preference", ["b13fa5c"]),
    ("4051f82", "2026-08-19", "2.0.0", ".claude/mise-config.md", "## Review notes", "added",
     "Retrospective-adopted: reviewer term in Test exceptions, Review notes section in this repo's own config",
     "Adopt retrospective learnings: reviewer term in Test exceptions, Review notes section",
     "named-failure-in-a-real-run", []),

    # ------------------------------------------------------------------- 2.1.0
    ("133d2de", "2026-09-12", "2.0.0", "skills/next/roles/implementer.md", "progress-log entry / Checklist bullet", "reworked",
     "Checklist answers move out of the progress log into the commit body; Key changes and Deviations bounded",
     "`eric/attribution-3`'s `_progress.md` reached **56,330 words / 68 entries** ... **46% of it is dead weight.** Of 56,330 words, **26,172 are the `- Checklist:` bullets** (65 of them) that 2.0.0 added at `roles/implementer.md` step 6. [.mise/goals.md section A @5fabf88~1]",
     "named-failure-in-a-real-run", ["be77bae", "5d765fe", "b13fa5c"]),
    ("133d2de", "2026-09-12", "2.0.0", "skills/next/stages/execute.md", "documenter scope", "reworked",
     "Documenter rescoped from the whole branch diff to one task's diff, dispatched before the reviewer",
     "`fix/menu-pin`, commit `45b0bad8c` - **61 files, 349 insertions, 100 deletions, of which 345 added and 100 removed are comment lines**. One subagent, one commit, a 61-file comment rewrite. [.mise/goals.md section B @5fabf88~1]",
     "named-failure-in-a-real-run", ["be77bae", "5d765fe", "b13fa5c"]),
    ("133d2de", "2026-09-12", "2.0.0", "skills/next/stages/execute.md", "End-of-plan gate step 1 (documenter)", "removed",
     "The gate no longer re-runs the documenter on a repair that touched no documented code",
     "`stages/execute.md` re-runs the gate from step 1 \"after any commit lands past a finished gate (a repair, an acceptance-blocker fix)\", and step 1 is the documenter. That is how attribution-3 accumulated six whole-branch prose passes. [.mise/goals.md section C @5fabf88~1]",
     "named-failure-in-a-real-run", ["b13fa5c"]),
    ("133d2de", "2026-09-12", "2.0.0", "skills/next/roles/reviewer.md", "checklist verification", "reworked",
     "Reviewer verifies the implementer's recorded answers instead of re-deriving all rules",
     "Okven's checklist is at 14 of the 15-rule cap ... All 14 are answered by the implementer (`roles/implementer.md` step 5), again by every fix implementer, and independently again by the reviewer [.mise/goals.md section E @5fabf88~1]",
     "named-failure-in-a-real-run", ["be77bae", "5d765fe", "b13fa5c"]),
    ("be77bae", "2026-09-12", "2.0.0", "skills/next/stages/execute.md", "per-task defect router", "reworked",
     "Fix the per-task prose/not-prose defect router and compress the six instruction files",
     "task 01_01: review found the per-task defect router's bullets overlapping (single-pass mixed lists drop prose defects) and a malformed nested code span [.mise/_friction.md @5fabf88~1]",
     "named-failure-in-a-real-run", ["5d765fe"]),
    ("5d765fe", "2026-09-12", "2.0.0", "skills/next/stages/execute.md", "two-pass mode contract", "reworked",
     "Two-pass rules collapsed into one contract; acceptance's narrowed prose sweep and the documenter heading discriminator dropped",
     "correction: instruction files must stay concise and targeted; task 01_01 grew the six files 3793 -> 4406 words (+16%), against the branch's own purpose since every subagent reads them [.mise/_friction.md @5fabf88~1]",
     "named-failure-in-a-real-run", ["b13fa5c"]),
    ("b13fa5c", "2026-09-12", "2.1.0", "skills/next/", "mise 2.1.0 squash", "reworked",
     "Squash onto main: per-task documenter, checklist answers in commits, verifying reviewer; skills md 9795 -> 9974 words",
     "Fixes the token and wall-clock regression 2.0.0 introduced, measured on two okven runs",
     "named-failure-in-a-real-run", []),
    ("b13fa5c", "2026-09-12", "2.1.0", "skills/next/references/interaction.md", "critic-gate round budget", "added",
     "Explicitly NOT changed in 2.1.0 despite both okven runs exhausting the budget",
     "**The critic-gate round budget** (the `4e828af` non-convergence stall). Both branches ran both artifacts to `budget exhausted`, but the user chose to leave the loop alone; it stays as-is. [.mise/goals.md 'Explicitly out of scope' @5fabf88~1]",
     "owner-preference", []),
]

FIELDS = ("sha", "date", "version", "file", "anchor", "change", "what",
          "statedReason", "trigger", "laterChurn")

for row in ROWS:
    obj = dict(zip(FIELDS, row))
    assert obj["trigger"] in {
        "named-failure-in-a-real-run", "owner-preference", "speculative",
        "refactor", "unknown"}, obj
    assert obj["change"] in {"added", "removed", "reworked"}, obj
    assert len(obj["what"].split()) <= 20, obj["what"]
    sys.stdout.write(json.dumps(obj) + "\n")
